openapi: 3.0.3
info:
  title: Ping API
  version: 1.0.0
paths:
  /ping:
    get:
      summary: Vérifie si le serveur est vivant
      description: Retourne "pong" si le serveur répond correctement
      responses:
        '200':
          description: Réponse réussie
          content:
            text/plain:
              schema:
                type: string
              example: pong
