openapi: 3.0.3
info:
  title: Users API
  version: 1.0.0
paths:
  /users:
    get:
      summary: Récupérer la liste des utilisateurs
      description: Retourne une liste paginée des utilisateurs
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
          description: Numéro de la page
        - name: size
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
          description: Taille de la page
      responses:
        '200':
          description: Liste des utilisateurs retrouvés
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    email:
                      type: string
              example:
                - id: 1
                  name: Alice
                  email: alice@example.com
                - id: 2
                  name: Bob
                  email: bob@example.com
        '400':
          description: Mauvais types de paramètres fournis
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: "Bad types for provided query parameters"
